### ISSUE TITLE
joshuto可以做到选中所有匹配的内容吗

### ISSUE THREAD

**Issue by shinonomeow** [MrSeaWave/dotfiles#1]
看快捷键没有类似的功能,要怎么能做到呢

**Comment by MrSeaWave** [comment]
可以，你可以尝试使用 `select -all *.png` 这种方式。

例如我需要选择匹配到的 testxxxx.json 文件

运行 `select -all test*.json` 即可选中。

![image](https://github.com/MrSeaWave/dotfiles/assets/21967852/1fd3f134-a708-49da-9648-2abff29f7098)

具体用法可查看[joshuto](https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#select-select-current-file)

![image](https://github.com/MrSeaWave/dotfiles/assets/21967852/a40fa964-29da-4c8c-aedc-94f8d7705f41)

**Comment by shinonomeow** [comment]
感谢,我在仔细看看
